version: "3.0" 

services:
  db:
    image: postgres
    environment: 
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:${PORT}
    volumes:
      - .:/code
    ports:
      - "${PORT}:${PORT}" 
    depends_on:
      - db 

    stdin_open: true
    tty: true

volumes:
  dbdata: